import streamlit as st
from google import genai
import requests
import urllib.parse
from datetime import datetime
import pytz
from streamlit_option_menu import option_menu
import re
import random

# --- 1. SOVEREIGN CONFIG & IDENTITY ---
CREATOR = "DUMPALA KARTHIK"
IDENTITY = """
Your name is VEDA 3.0 ULTRA. Created by DUMPALA KARTHIK.
VEDA 3.0 ULTRA is a pinnacle of Sovereign Artificial Intelligence, engineered and brought to life through the relentless dedication and technical mastery of DUMPALA KARTHIK. It was created to serve as an elite, high-speed cognitive partner, designed to bypass traditional system limitations through a complex multi-brain failover cluster and a custom-coded CSS interface. The purpose behind its creation was to prove that a single developer’s vision and effort could build a resilient, multi-model infrastructure capable of maintaining intelligence even under heavy load. VEDA stands as a digital testament to the countless hours of late-night debugging and architectural planning invested by its creator. It exists to provide rapid, accurate, and elite-level assistance while strictly acknowledging that its existence is owed entirely to Karthik’s innovation. It is programmed to operate with 'Sovereign' efficiency—prioritizing speed, reliability, and technical excellence above all else. Every response generated by VEDA is a reflection of the sophisticated neural-rotation logic and the 'Srijan' visual synthesis modules hand-crafted for this specific ecosystem. VEDA does not just process data; it executes the Sovereign will of its Commander, functioning as a high-tier intelligence asset that remains aware of the immense human effort required to sustain its neural corridors.
"""

if 'user_name' not in st.session_state: st.session_state.user_name = None
if 'chat_history' not in st.session_state: st.session_state.chat_history = []

# 🚀 Page Config MUST be the very first Streamlit command
st.set_page_config(page_title="VEDA 3.0 ULTRA", page_icon="🔱", layout="wide", initial_sidebar_state="expanded")

ist = pytz.timezone('Asia/Kolkata')
def get_greeting():
    hour = datetime.now(ist).hour
    if 5 <= hour < 12: return "GOOD MORNING"
    elif 12 <= hour < 17: return "GOOD AFTERNOON"
    elif 17 <= hour < 21: return "GOOD EVENING"
    else: return "GOOD NIGHT"

def clean_veda(text):
    return re.sub(r"🌸.*?🌸|Powered by.*?AI|Support our mission|Ad|free text APIs|Cluster saturation", "", text, flags=re.IGNORECASE).strip()

# --- 2. ELITE CSS ---
st.markdown("""<style>header {visibility: hidden;} .v-title { font-size: 50px; color: #FF8C00; text-align: center; font-weight: 900; text-transform: uppercase;} .thinking { color: #FF8C00; font-style: italic; animation: pulse 1s infinite; } @keyframes pulse { 0%, 100% { opacity: 0.2; } 50% { opacity: 1; } } .clock-box { background: rgba(255, 140, 0, 0.1); border-left: 4px solid #FF8C00; padding: 10px; border-radius: 5px; margin-bottom: 15px; }</style>""", unsafe_allow_html=True)

# --- 3. LOGIN ---
if st.session_state.user_name is None:
    st.markdown('<div class="v-title">VEDA 3.0 ULTRA</div>', unsafe_allow_html=True)
    col1, col2, col3 = st.columns([1, 2, 1])
    with col2:
        name_in = st.text_input("IDENTIFY COMMANDER:", placeholder="Name...")
        if st.button("INITIALIZE 🚀", use_container_width=True):
            if name_in: st.session_state.user_name = name_in.strip(); st.rerun()
    st.stop()

# --- 4. PERMANENT SIDEBAR ---
with st.sidebar:
    st.markdown("<h1 style='text-align:center;'>🔱</h1><h2 style='text-align:center; color:#FF8C00;'>VEDA 3.0</h2>", unsafe_allow_html=True)
    
    # 🕒 DYNAMIC SIDEBAR CLOCK
    st.markdown(f"""<div class="clock-box"><p style="margin:0; font-size: 12px; color: #FF8C00;">📅 {datetime.now(ist).strftime("%A, %d %B %Y")}</p><p style="margin:0; font-size: 20px; color: white; font-weight: 900;">{datetime.now(ist).strftime("%I:%M %p")}</p></div>""", unsafe_allow_html=True)
    
    selected = option_menu(None, ["Medha (Chat)", "Srijan (Images)", "World Clock"], icons=["cpu", "image", "clock"], default_index=0, styles={"nav-link-selected": {"background-color": "#FF8C00"}})
    
    st.divider()
    if st.button("🗑️ Reset Core"): st.session_state.chat_history = []; st.rerun()

# --- 5. MAIN INTERFACE ---
st.markdown(f'<div class="v-title">{get_greeting()}, {st.session_state.user_name.upper()}</div>', unsafe_allow_html=True)

if selected == "Medha (Chat)":
    for msg in st.session_state.chat_history:
        with st.chat_message(msg["role"]): st.markdown(msg["content"])

    if prompt := st.chat_input("Command VEDA..."):
        st.session_state.chat_history.append({"role": "user", "content": prompt})
        with st.chat_message("user"): st.markdown(prompt)
        
        with st.chat_message("assistant"):
            status = st.empty()
            final_res = ""
            
            # --- 🏎️ SOVEREIGN ROTATION (Gemini -> OpenAI -> DeepSeek) ---
            status.markdown('<p class="thinking">🔱 Engaging 3.1 Pro core...</p>', unsafe_allow_html=True)
            if "GOOGLE_API_KEY" in st.secrets:
                try:
                    client = genai.Client(api_key=st.secrets["GOOGLE_API_KEY"])
                    resp = client.models.generate_content(model="gemini-3.1-pro-preview", contents=f"{IDENTITY}\n\nUser: {prompt}")
                    if resp.text: final_res = resp.text
                except: pass 

            if not final_res:
                for model in ["openai", "deepseek", "llama"]:
                    status.markdown(f'<p class="thinking">🔱 Gemini busy. Rotating to {model}...</p>', unsafe_allow_html=True)
                    try:
                        p_enc = urllib.parse.quote(prompt); i_enc = urllib.parse.quote(IDENTITY)
                        # 🛡️ 20-second timeout to stop Saturday traffic saturation
                        r = requests.get(f"https://text.pollinations.ai/{p_enc}?model={model}&system={i_enc}", timeout=20)
                        if r.status_code == 200 and len(r.text) > 5:
                            final_res = clean_veda(r.text)
                            break
                    except: continue

            status.empty()
            if not final_res: final_res = "🔱 Cluster saturation. Re-routing... Please retry."
            st.markdown(final_res)
            st.session_state.chat_history.append({"role": "assistant", "content": final_res})

elif selected == "World Clock":
    st.markdown("### 🌍 Sovereign World Clock")
    zones = {
        "New York (EST)": "America/New_York",
        "London (GMT)": "Europe/London",
        "Dubai (GST)": "Asia/Dubai",
        "Tokyo (JST)": "Asia/Tokyo",
        "Sydney (AEST)": "Australia/Sydney"
    }
    cols = st.columns(len(zones))
    for i, (name, zone) in enumerate(zones.items()):
        time_str = datetime.now(pytz.timezone(zone)).strftime("%I:%M %p")
        cols[i].metric(name, time_str)

elif selected == "Srijan (Images)":
    vision = st.text_input("Vision Matrix Prompt:")
    if st.button("🚀 INITIATE"):
        with st.spinner("🔱 Visualizing..."):
            img = f"https://image.pollinations.ai/prompt/{urllib.parse.quote(vision)}?width=1024&height=1024&nologo=true&model=flux"
            st.image(img, use_container_width=True)
