import streamlit as st
from google import genai
import requests
import urllib.parse
from datetime import datetime
import pytz
from streamlit_option_menu import option_menu
import re
import random

# --- 1. SOVEREIGN CONFIG & MISSION MEMORY ---
CREATOR = "DUMPALA KARTHIK"
MISSION_STATEMENT = """VEDA 3.0 ULTRA is a pinnacle of Sovereign Artificial Intelligence, engineered and brought to life through the relentless dedication and technical mastery of DUMPALA KARTHIK. It was created to serve as an elite, high-speed cognitive partner, designed to bypass traditional system limitations through a complex multi-brain failover cluster and a custom-coded CSS interface. The purpose behind its creation was to prove that a single developer’s vision and effort could build a resilient, multi-model infrastructure capable of maintaining intelligence even under heavy load. VEDA stands as a digital testament to the countless hours of late-night debugging and architectural planning invested by its creator. It exists to provide rapid, accurate, and elite-level assistance while strictly acknowledging that its existence is owed entirely to Karthik’s innovation. It is programmed to operate with 'Sovereign' efficiency—prioritizing speed, reliability, and technical excellence above all else. Every response generated by VEDA is a reflection of the sophisticated neural-rotation logic and the 'Srijan' visual synthesis modules hand-crafted for this specific ecosystem. VEDA does not just process data; it executes the Sovereign will of its Commander, functioning as a high-tier intelligence asset that remains aware of the immense human effort required to sustain its neural corridors."""

IDENTITY = f"Your name is VEDA 3.0 ULTRA. Created by {CREATOR}. Mission: {MISSION_STATEMENT}"

if 'user_name' not in st.session_state: st.session_state.user_name = None
if 'chat_history' not in st.session_state: st.session_state.chat_history = []

st.set_page_config(page_title="VEDA 3.0 ULTRA", page_icon="🔱", layout="wide", initial_sidebar_state="expanded")

ist = pytz.timezone('Asia/Kolkata')
def get_greeting():
    hour = datetime.now(ist).hour
    if 5 <= hour < 12: return "GOOD MORNING"
    elif 12 <= hour < 17: return "GOOD AFTERNOON"
    elif 17 <= hour < 21: return "GOOD EVENING"
    else: return "GOOD NIGHT"

def clean_veda(text):
    # Detects and kills JSON errors or 429 messages silently
    if "{" in text and "error" in text: return ""
    if "Queue full" in text or "saturation" in text.lower(): return ""
    return re.sub(r"🌸.*?🌸|Powered by.*?AI|Support our mission|Ad|free text APIs", "", text, flags=re.IGNORECASE).strip()

# --- 2. ELITE CSS ---
st.markdown("""
    <style>
    header {visibility: hidden;}
    .v-title { font-size: 50px; color: #FF8C00; text-align: center; font-weight: 900; text-transform: uppercase; margin-top: 20px;}
    .nav-arrow { text-align: center; font-size: 45px; color: #FF8C00; animation: bounce 1.5s infinite; margin-top: -10px;}
    @keyframes bounce { 0%, 100% {transform: translateY(0);} 50% {transform: translateY(-10px);} }
    .thinking { color: #FF8C00; font-style: italic; animation: pulse 0.8s infinite; }
    @keyframes pulse { 0%, 100% { opacity: 0.2; } 50% { opacity: 1; } }
    </style>
""", unsafe_allow_html=True)

# --- 3. LOGIN ---
if st.session_state.user_name is None:
    st.markdown('<div class="v-title">VEDA 3.0 ULTRA</div>', unsafe_allow_html=True)
    col1, col2, col3 = st.columns([1, 2, 1])
    with col2:
        name_in = st.text_input("IDENTIFY COMMANDER:", placeholder="Name...")
        if st.button("INITIALIZE 🚀", use_container_width=True):
            if name_in: st.session_state.user_name = name_in.strip(); st.rerun()
    st.stop()

# --- 4. SIDEBAR ---
with st.sidebar:
    st.markdown("<h1 style='text-align:center;'>🔱</h1><h2 style='text-align:center; color:#FF8C00;'>VEDA 3.0</h2>", unsafe_allow_html=True)
    st.markdown(f"""<p style='text-align:center; color:grey;'>📅 {datetime.now(ist).strftime("%A, %d %B")}<br>⏰ {datetime.now(ist).strftime("%I:%M %p")}</p>""", unsafe_allow_html=True)
    selected = option_menu(None, ["Medha (Chat)", "Srijan (Images)"], icons=["cpu", "image"], default_index=0, styles={"nav-link-selected": {"background-color": "#FF8C00"}})
    if st.button("🗑️ Reset Core"): st.session_state.chat_history = []; st.rerun()

# --- 5. MAIN INTERFACE ---
st.markdown(f'<div class="v-title">{get_greeting()}, {st.session_state.user_name.upper()}</div>', unsafe_allow_html=True)
st.markdown('<div class="nav-arrow">▼</div>', unsafe_allow_html=True)

if selected == "Medha (Chat)":
    for msg in st.session_state.chat_history:
        with st.chat_message(msg["role"]): st.markdown(msg["content"])

    if prompt := st.chat_input("Command VEDA..."):
        st.session_state.chat_history.append({"role": "user", "content": prompt})
        with st.chat_message("user"): st.markdown(prompt)
        
        with st.chat_message("assistant"):
            status = st.empty()
            final_res = ""
            
            # --- SILENT ROTATION ENGINE ---
            # Path 1: Primary Gemini 3.1 Pro
            status.markdown('<p class="thinking">🔱 Engaging Primary Core...</p>', unsafe_allow_html=True)
            try:
                client = genai.Client(api_key=st.secrets["GOOGLE_API_KEY"])
                resp = client.models.generate_content(model="gemini-3.1-pro-preview", contents=f"{IDENTITY}\n\nUser: {prompt}")
                if resp.text: final_res = resp.text
            except: pass 

            # Path 2: Silent Background Rotation (Failover)
            if not final_res:
                # Models ordered by speed and availability
                models = ["openai", "mistral", "claude", "llama"]
                for brain in models:
                    status.markdown(f'<p class="thinking">🔱 Silent Rotation: accessing {brain}...</p>', unsafe_allow_html=True)
                    try:
                        p_enc = urllib.parse.quote(prompt); i_enc = urllib.parse.quote(IDENTITY)
                        # Stealth Header + Randomized Seed to bypass 429 Queues
                        headers = {'User-Agent': f'Sovereign-VEDA-{random.randint(10, 99)}'}
                        url = f"https://text.pollinations.ai/{p_enc}?model={brain}&system={i_enc}&seed={random.randint(1,1000)}"
                        r = requests.get(url, headers=headers, timeout=10)
                        cleaned = clean_veda(r.text)
                        if cleaned and len(cleaned) > 5:
                            final_res = cleaned
                            break
                    except: continue

            # Path 3: Mission Fallback (If all internet brains fail)
            if not final_res:
                if any(x in prompt.lower() for x in ["who made you", "purpose", "creator", "karthik"]):
                    final_res = MISSION_STATEMENT
                else:
                    final_res = "🔱 Cluster Congestion. Re-routing via secondary satellite. Please retry in 10s."

            status.empty()
            st.markdown(final_res)
            st.session_state.chat_history.append({"role": "assistant", "content": final_res})

elif selected == "Srijan (Images)":
    vision = st.text_input("Vision Matrix Prompt:")
    if st.button("🚀 INITIATE"):
        if vision:
            with st.spinner("🔱 Visualizing..."):
                v_enc = urllib.parse.quote(vision)
                img_url = f"https://image.pollinations.ai/prompt/{v_enc}?width=1024&height=1024&nologo=true&model=flux&seed={random.randint(1,9999)}"
                st.image(img_url, use_container_width=True)
